[package]
name = "example-01-microservice"
version = "0.1.0"
authors = ["root"]

[dependencies]
tokio-line = { git = "https://github.com/tokio-rs/tokio-line" }
service-fn = { git = "https://github.com/tokio-rs/service-fn" }
